---
# Using Debian Bookworm base for glibc compatibility
# (opencode-ai ships pre-compiled native binaries that require glibc)
# Includes: S6-Overlay, Bashio, TempIO
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
args:
  # Pin versions for reproducible builds (use 'latest' for auto-updates)
  OPENCODE_VERSION: "latest"
  TTYD_VERSION: "1.7.7"
labels:
  org.opencontainers.image.title: "HA OpenCode"
  org.opencontainers.image.description: "AI coding agent for Home Assistant (Integrated Opencode web UI)"
  org.opencontainers.image.source: "https://github.com/szampardi/ha_opencode"
  org.opencontainers.image.licenses: "Unlicense"
  org.opencontainers.image.vendor: "SILVANO ZAMPARDI"
